name: solace-vmr-warden-deployment
director_uuid: <%= `bosh status --uuid` %>

releases:
- name: docker
  version: latest
- name: solace-vmr
  version: latest

compilation:
  workers: 1
  network: test-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common-resource-pool
  network: test-network
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties:
    name: random

networks:
- name: test-network
  type: manual
  subnets:
  - range: 10.244.0.0/28
    gateway: 10.244.0.1
    static:
      - 10.244.0.2
      - 10.244.0.3
    cloud_properties:
      name: random
  - range: 10.244.0.16/28
    gateway: 10.244.0.17
    static: []
    cloud_properties:
      name: random

jobs:
- name: community-vmr-job
  templates:
  -  {name: docker, release: docker}
  -  {name: prepare_vmr, release: solace-vmr}
  -  {name: containers, release: solace-vmr}
  -  {name: vmr_agent, release: solace-vmr}
  instances: 1
  persistent_disk: 20480
  resource_pool: common-resource-pool
  networks:
  - name: test-network
    static_ips:
      - 10.244.0.3
  properties:
    pool_name: 'Community-VMR'
    vmr_agent_port: 18080
    starting_port: 7000
    broker_user: 'solacedemo'
    broker_password: 'solacedemo'
    broker_hostname: 'solace-messaging.local.pcfdev.io'
    admin_password: 'admin'
    admin_user: 'admin'
    semp_port: 8080
    ssh_port: 2222
    cert_pem: "-----BEGIN CERTIFICATE-----\r\nMIIDdjCCAl4CCQD5bumg8Z3k6zANBgkqhkiG9w0BAQQFADB9MQswCQYDVQQGEwJD\r\nQTEQMA4GA1UECBMHT250YXJpbzEPMA0GA1UEBxMGS2FuYXRhMRwwGgYDVQQKExNQ\r\nQ0YtUG9DLUNlcnRpZmljYXRlMRMwEQYDVQQLEwpTb2xhY2UgUG9DMRgwFgYDVQQD\r\nEw9Tb2xhY2UtUG9DLVRpbGUwHhcNMTYwNzA2MDA1NDA4WhcNMjYwNzA0MDA1NDA4\r\nWjB9MQswCQYDVQQGEwJDQTEQMA4GA1UECBMHT250YXJpbzEPMA0GA1UEBxMGS2Fu\r\nYXRhMRwwGgYDVQQKExNQQ0YtUG9DLUNlcnRpZmljYXRlMRMwEQYDVQQLEwpTb2xh\r\nY2UgUG9DMRgwFgYDVQQDEw9Tb2xhY2UtUG9DLVRpbGUwggEiMA0GCSqGSIb3DQEB\r\nAQUAA4IBDwAwggEKAoIBAQC/CFIABLO/OhLB9Y1/qeDl+9zwEe2ho40SoiazCL9K\r\nNJa6WimGY7dZGCSLEs2x740i9Gh0+8BpTFjSRte98y45RfxvXYnGFpuy1ApJabJF\r\nFPbN6CR8KJvfn4j1hiX8j1q6rrNidRWY64JKB5OTWe/aTFa69/m7u2uXgVnYztFU\r\nmXxMnEMVDXJOLH32+wlNWYj/HiTDPZIJVxLYf+ebqPkpS8bQSKBNIxCyMDvVnyn7\r\nze0kSLpcFeclvkQj0Q/xXB8uo0Za2QGzDyTy7G5rzepRpmkX5/VSXLwZDw/27iNG\r\nVr2Cuggz5KwiMUl1UrIvPBVdNeMN1h+L/dq798BKqiBzAgMBAAEwDQYJKoZIhvcN\r\nAQEEBQADggEBAKcouo9Opx4IbmUJOjmCta6SuHWd6drilhrPb19tTqw8UaO9sEwq\r\nIe4WoTD7ymxkwXo1s6ynsvaC6DjuMKXyJ1lRrzd11J65DGXiJ+JGMrm37TQVEEFc\r\n34dpjW5NKqTRJufeps8uQYuldZoGS1N2E1L+5m/9g2Oatc/MgvmVM/8QekNT7SHb\r\nXV0sBviaVA5NAWtr9lFGSpkOsGMj5GC1Mx9X5/Dk6Uubfc3bdWcd0fCQqsHPynvU\r\n6mvx0i8go+eK0g+fxTdz0rhzV3i46kshMwmZ00FDyQStYpOTzPSi9r3evIHNYSn+\r\n272lPDt8nCbuISTpLqPwMs4tNwk+WPbuYDI=\r\n-----END CERTIFICATE-----\r\n"
    private_key_pem: "-----BEGIN RSA PRIVATE KEY-----\r\nMIIEowIBAAKCAQEAvwhSAASzvzoSwfWNf6ng5fvc8BHtoaONEqImswi/SjSWulop\r\nhmO3WRgkixLNse+NIvRodPvAaUxY0kbXvfMuOUX8b12JxhabstQKSWmyRRT2zegk\r\nfCib35+I9YYl/I9auq6zYnUVmOuCSgeTk1nv2kxWuvf5u7trl4FZ2M7RVJl8TJxD\r\nFQ1yTix99vsJTVmI/x4kwz2SCVcS2H/nm6j5KUvG0EigTSMQsjA71Z8p+83tJEi6\r\nXBXnJb5EI9EP8VwfLqNGWtkBsw8k8uxua83qUaZpF+f1Uly8GQ8P9u4jRla9groI\r\nM+SsIjFJdVKyLzwVXTXjDdYfi/3au/fASqogcwIDAQABAoIBADUhKEUvCZrOmPbu\r\nxzrRUWZFRS5TniaNaSfchyzV6vXFaIJNnyzsQMr7pvYy9ZheSn+FQCQA/IOMo0tg\r\nPpJqttlg+JM0jaPVF9qFlJLUXatO6FFeFf+d/7QTF7FJbPkwGYjAG83vSGFuZp8W\r\nOloJ8mZhQuHfI8qtln/djtJ4uslvJ4TkFtHc90rjiBgjW1CJ655ras4BrWQMhYCR\r\nZdYl4pCDZjW7r6a9YBK4IyBF55gOfyOBQ0z76PumV7QJ2MmvwJcrrmjCHnhZb8kI\r\nWcBPPGQGmCcZNGD+oXq++J5rGEaUKAr8sC03LSK1kKlGjj2hUCsll5bGAveR5LP/\r\nQZDqxOkCgYEA5appi5kPXTcTiA70uLQfAXumG2h32UMbSrQ6kVirIQ+YOVPvqmH/\r\n156iDrFpUdWWiDyJJC66gHZm97QwSpIsihTe7xFQAgHM29pH/xyE0PIHCOqC9i1d\r\nnYFlXwOGIGWUf7cLan05GTsZ+BdOYEbA3IqujwgK5TJ0gakgADOdtCcCgYEA1O/f\r\nfVMDDVp5bCuzn/84iGErlf8Je9m+TyfsicV9DfxgL1NWV8PE0H7JaBxtzUdnV2TU\r\nES5Awg3xuC9HmeF16pgge5LX2ELhO2VMbmbMFoEwyDazjuhHix0Vv8NOTIj4h/AM\r\ncvYtXBJ+oN1f8WM6S1dmC4ffAc9geQ5K8LnMZNUCgYBWe/io1+eAO6hAORmQoEt4\r\nvH5NneZbyzhwxjOz3gb7OSsik2gR6jt0j8kI7WfyqBK6lMkz9eDHVU7rAlCZFDhv\r\nevKEZimRx+nD9IveFngxUqKxidXtLCIvmLV6tRICCx6DhYNoA2XICYh68xPRj3M6\r\n2YJoXCf2LSzQUsa5LLa7SwKBgQCAESThQyP6zAdrP31xJRbjL03/kLwrePI0uVZS\r\nJizoVHmk/QJZFq0wmJCZxT9kzyUgMsw46RCZpblThVwS+L7qsUQYDmEy+EZuaqZl\r\nX/4vKtQkFoI32QvuZzfFdbmJ3ndbisxx+A2f6p+uMHabv4o39gCxvq4pcIgdRrNb\r\nxONhYQKBgHLVInaxLelVNDvuSuN0dRei4PmdIBmWlHYRhvWyFR3SeKRD5TZNyWhJ\r\ncdYt6FMKAjowMdPEk4yytW2yPS0EWs69Sj/uDNsaeOSOPrvKrNI0Hwb4xLO9KD0c\r\neMav3A00I3YI2JYln/q02M2IV4Fn2HcVKndqfojn479/jUH/rMq0\r\n-----END RSA PRIVATE KEY-----\r\n"
    containers:
      - name: solace
        image: solace-bosh
        dockerfile: |
          FROM solace-app:latest-community

          RUN \
            echo 'admin' | passwd --stdin admin && \
            echo 'support' | passwd --stdin support && \
            echo 'solace1' | passwd --stdin root && \
            echo '#!/bin/bash' > /sbin/dhclient && \
            echo 'exec tail -f /dev/null' >> /sbin/dhclient && \
            echo '3a:40:d5:42:f4:86' > /usr/sw/.nodeIdentifyingMacAddr && \
            chmod +x /sbin/dhclient
        env_vars:
         - "NODE_TYPE=MESSAGE_ROUTING_NODE"
         - "SSHD_PORT=2222"
         - "ALWAYS_DIE_ON_FAILURE=1"
        net: host
        privileged: true
        uts: host
        volumes:
        - /var/vcap/store/prepare_vmr/volumes/jail:/usr/sw/jail
        - /var/vcap/store/prepare_vmr/volumes/var:/usr/sw/var
        - /var/vcap/store/prepare_vmr/volumes/internalSpool:/usr/sw/internalSpool
        - /var/vcap/store/prepare_vmr/volumes/adbBackup:/usr/sw/adb
        - /var/vcap/store/prepare_vmr/volumes/adb:/usr/sw/internalSpool/softAdb
        - /dev/shm:/dev/shm
